#!/bin/bash

set -eu

current_arch="$(dpkg --print-architecture)"
arch="${1:-$current_arch}"

if [ "$arch" != 'amd64' ] && [ "$arch" != 'i386' ]; then
  >&2 echo 'Only amd64 and i386 are supported'
  exit 1
fi

version="$(jq -r '.version' variables.json)-$(date +'%s')"
tarball="builds/rootfs-$arch-$version.tar.xz"
rootfs="$(mktemp -d rootfs.XXX)"

debootstrap --arch="$arch" \
            --force-check-gpg \
            --no-merged-usr \
            --variant=minbase \
            --include=python,python-apt \
              stable \
              "$rootfs" \
              https://deb.debian.org/debian/

ROOTFS="$rootfs" ansible-playbook \
    --inventory=ansible/inventory.yml \
  ansible/rootfs.yml

tar -Jp --numeric-owner -C "$rootfs" -f "$tarball" -c .
rm -rf "$rootfs"

docker image import "$tarball" "conn/rootfs-$arch:$version"

if [ "$arch" == "amd64" ]; then
  docker tag "conn/rootfs-amd64:$version" "conn/rootfs:$version"
fi

echo "VERSION: $version"
