#!/bin/bash

set -eu

version="$(jq -r '.version' variables.json)-$(date +'%s')"
tarball="builds/rootfs-$version.tar.xz"
rootfs="$(mktemp -d rootfs.XXX)"

debootstrap --arch=amd64 \
            --force-check-gpg \
            --no-merged-usr \
            --variant=minbase \
            --include=python,python-apt \
              stable \
              "$rootfs" \
              https://deb.debian.org/debian/

ROOTFS="$rootfs" ansible-playbook \
    --inventory=ansible/inventory.yml \
  ansible/rootfs.yml

tar -Jp --numeric-owner -C "$rootfs" -f "$tarball" -c .
rm -rf "$rootfs"

docker image import "$tarball" "conn/rootfs:$version"

echo "VERSION: $version"
