---
- name: conn.accounts
  src: https://github.com/conn/ansible-role-accounts
  tag: v1.0.0
  version: bc9d56b36e451b52e4e68728cce981970df63e74

- name: conn.permissions
  src: https://github.com/conn/ansible-role-permissions
  tag: v1.0.1
  version: 159cff2143efe5f18d377975077695c89b12be33

- name: conn.scrub
  src: https://github.com/conn/ansible-role-scrub
  tag: v1.1.1
  version: 4c6cbba72763268350ed41db2961056c72e457da

- name: conn.rootfs
  src: https://github.com/conn/ansible-role-rootfs
  tag: v2.0.1
  version: f71a8b4ef1a82a1711f18dbd43e2fba3d5d8d95d
